### ISSUE TITLE
add error handling for RPC calls

### ISSUE THREAD

**Issue by simevo** [simevo/fatturapa-testui#1]
when RPC calls fail, print troubleshooting messages to `console.err` and make that discreetely visibile (i.e. with background color change, icon status, [toast notication](https://uxplanet.org/toast-notification-or-dialog-box-ae32ad53106d) ...)

modal pop-up is not OK because we may get many RPC call failures at once and we not want to flood the user with notifications

**Comment by Valamiro** [comment]
https://notifyjs.jpillora.com/

**Comment by simevo** [comment]
https://github.com/apvarun/toastify-js
